version: "3.9"
services:
  db:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  web:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - db
